[package]
name = "coqrs"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
argon2 = "0.5.3"
async-trait = "0.1.89"
axum = { version = "0.8.4", features = ["macros"] }
derive-new = "0.7.0"
derive_builder = "0.20.2"
derive_more = { version = "2.0.1", features = ["full"] }
dotenvy = "0.15.7"
hyper = { version = "1.7.0", features = ["full"] }
nutype = { version = "0.6.2", features = ["regex", "serde"] }
rand_core = { version = "0.9.3", features = ["os_rng"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sqlx = { version = "0.8.6", features = ["postgres", "macros", "uuid","runtime-tokio"]}
tokio = { version = "1", features = ["full"] }
tonic = "0.14.2"
tonic-reflection = "0.14.2"
tonic-web = "0.14.2"
tonic-prost = "0.14.2"
prost = "0.14.1"
tower = { version = "0.5.2", features = ["full"] }
tower-http = { version = "0.6.6", features = ["trace"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
uuid = {version = "1" , features = ["serde", "v7"]}
jsonwebtoken = "9.3.1"
chrono = { version = "0.4.42", features = ["serde"] }
thiserror = "1.0.61"

[build-dependencies]
regex = "1.11.2"
glob = "0.3.3"
tonic-prost-build = "0.14.2"
