mod user_service;
mod email_verification_service;
mod session_service;
mod password_service;
mod password_reset_service;
mod profile_service;
mod account_service;
mod search_service;
mod activity_logging_service;
mod rate_limiting_service;
mod account_lockout_service;
mod rbac_service;
pub mod pagination_service;
pub mod bulk_operations_service;

pub use user_service::UserService;
pub use email_verification_service::EmailVerificationService;
pub use session_service::SessionService;
pub use password_service::PasswordService;
pub use password_reset_service::PasswordResetService;
pub use profile_service::{ProfileService, UpdateProfileRequest, UpdateAccountRequest};
pub use account_service::{AccountService, DeactivateAccountRequest, ReactivateAccountRequest, DeleteAccountRequest, SuspendAccountRequest};
pub use search_service::{SearchService, UserSearchFilters, AdvancedSearchFilters, UserSearchResult, PublicUser, UserSuggestion};
pub use activity_logging_service::{ActivityLoggingService, ActivityType, UserActivity, UserActivityResponse, ActivityFilters, ActivityResult, ActivityStats};
pub use rate_limiting_service::{RateLimitingService, AuthAttempt, RateLimitResult, RateLimitStats, FailingIpInfo, RateLimitQuery, UserStats};
pub use account_lockout_service::{AccountLockoutService, LockoutType, LockoutStatus, LockoutInfo, AccountLockoutRecord, LockoutHistoryItem, LockoutStats, ManualLockoutRequest, UnlockAccountRequest};
pub use rbac_service::{RbacService, Role, Permission, UserRole, PermissionGrant, UserWithRole, AssignRoleRequest, CreateRoleRequest};
pub use bulk_operations_service::{BulkOperationsService, BulkCreateUserRequest, BulkCreateUserResponse, BulkUpdateStatusRequest, BulkUpdateStatusResponse, BulkDeleteUserRequest, BulkDeleteUserResponse, BulkOperationResult, BulkOperationError, BulkOperationStatus};
